# Generated by Django 2.2.6 on 2019-10-30 09:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('data_type', models.CharField(max_length=16)),
                ('optional', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('PUT', 'put'), ('DELETE', 'delete')], max_length=16)),
                ('request_url', models.CharField(max_length=1024)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiRequestVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('api_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentor.ApiRequest')),
                ('removed_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentor.ApiFields')),
            ],
        ),
        migrations.AddField(
            model_name='apifields',
            name='api_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentor.ApiRequest'),
        ),
    ]
